#ifndef H_IOCOMMON
#define H_IOCOMMON
#include <winioctl.h>
#define SIOCTL_TYPE 0x00008810
//增加特征码
#define IADS_DRIVER_ADDCODE (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1000, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
//发送网关IP,MAC
#define IADS_DRIVER_NETGATE (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1001, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
//数据包过滤开关
#define IADS_PACKET_FILTER (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1002, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
//禁止PING入开关
#define IADS_ICMP_FILTER  (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1003, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
//防ARP欺骗开关
#define IADS_ANTIARP (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1004, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
//读取新的攻击日志
#define IADS_NEWATTACK_EVENT (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1005, METHOD_NEITHER, FILE_ANY_ACCESS)
//传递通信事件
#define IO_REFERENCE_EVENT (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1006, METHOD_NEITHER, FILE_ANY_ACCESS)
//清除通信事件
#define IO_CLEAR_EVENT (ULONG) CTL_CODE(SIOCTL_TYPE, 0x1007, METHOD_NEITHER, FILE_ANY_ACCESS)
#endif
