//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Defender.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ADVANCESETTING_DIALOG       102
#define IDD_PROTECT_START               107
#define IDD_PROTECT_AUTORUN             107
#define IDR_MAINFRAME                   128
#define IDR_DEFENDTYPE                  129
#define IDD_PROTECT_SET                 130
#define IDD_BASIC_PROCESS               131
#define IDD_BASIC_CONNECT               132
#define IDB_TOOLBAR_COLD                133
#define IDB_TOOLBAR_HOT                 134
#define IDR_HOTBAR                      135
#define IDR_PROCESS                     139
#define IDR_CONNECT                     142
#define IDD_BASIC_LOCAL                 143
#define IDD_PROTECT_NETLOG              145
#define IDD_PROTECT_HOSTLOG             146
#define IDR_NETLOG                      147
#define IDR_TRAY                        148
#define IDB_IADS                        150
#define IDD_LOADCODE                    151
#define IDD_BASIC_MODULE                152
#define IDB_LOADCODE                    157
#define IDD_PROTECT_SERVICE             158
#define IDR_SERVICE                     159
#define IDD_PROTECT_REGISTER            160
#define IDB_ALL                         162
#define IDR_AUTORUN                     163
#define IDD_PROTECT_HOSTS               164
#define IDR_HOSTS                       165
#define IDD_EDITHOSTS                   167
#define IDR_PORTLIST                    168
#define IDD_DANGER                      169
#define IDR_IPLIST                      170
#define IDR_MESLIST                     171
#define IDD_PROTECT_DIALOG              174
#define IDD_WHITE_DIALOG                175
#define IDD_DIALOG1                     176
#define IDC_CONNECT_LIST                1000
#define IDC_PROCESS_LIST                1001
#define IDC_ADAPTER_LIST                1009
#define IDC_MACADDR                     1012
#define IDC_NETGATEMAC                  1013
#define IDC_IPADDR                      1014
#define IDC_PCOUNT                      1015
#define IDC_LIVEPCNUM                   1016
#define IDC_NETMASK                     1017
#define IDC_NETGATE                     1018
#define IDC_LIVEHOST_LIST               1019
#define IDC_ATTACKLOG_LIST              1020
#define IDC_PACKETFILTER_CHECK          1021
#define IDC_ANTIARP_CHECK               1022
#define IDC_ICMPFILTER_CHECK            1023
#define IDC_PLAYALLROLE                 1024
#define IDC_TOTALCOUNT                  1025
#define IDC_PERCENT                     1026
#define IDC_FINISHCOUNT                 1027
#define IDC_TIPS                        1029
#define IDC_MODULE_LIST                 1030
#define IDC_REFRESH_BUTTON              1031
#define IDC_SOFT_BUTTON                 1032
#define IDC_FORCEALL_BUTTON             1033
#define IDC_BADARP_LIST                 1033
#define tr                              1034
#define IDC_BADARP_LIST2                1034
#define IDC_SERVICE_LIST                1034
#define IDC_FORCE_BUTTON                1035
#define IDC_REGISTER_LIST               1035
#define IDC_MESLIST                     1038
#define IDC_AUTORUN_LIST                1041
#define IDC_HOSTS_LIST                  1042
#define IDC_IPADDRESS                   1043
#define IDC_DOMAIN                      1044
#define IDC_CHECK                       1045
#define IDC_APPLY                       1046
#define IDC_ADVANCESETTING              1047
#define IDC_OSLIST                      1048
#define IDC_ICMPACCEPT                  1049
#define IDC_PORTLIST                    1050
#define IDC_ADDPORT                     1051
#define IDC_PORTNUM                     1052
#define IDC_PROTOCOLLIST                1053
#define IDC_STATELIST                   1054
#define IDC_SCRIPTLIST                  1056
#define IDC_SAVEHOST                    1057
#define IDC_CLOSE                       1058
#define IDC_IPLIST                      1059
#define IDC_ADDHOST                     1061
#define IDC_END_BUTTON                  1062
#define IDC_REFUSE_BUTTON               1063
#define IDC_IGNORE_BUTTON               1064
#define IDC_ADD_BUTTON                  1065
#define IDC_DISCRIBE                    1066
#define IDC_EDIT1                       1069
#define IDC_INFO_EDIT                   1069
#define IDC_INFO_ETIT                   1069
#define IDC_PROTECT_EDIT                1069
#define IDC_PROC_EDIT                   1069
#define IDC_SCCOUNT                     1073
#define IDC_PACKETFILTER                1074
#define IDC_ARPFILTER                   1075
#define IDC_ICMPFILTER                  1076
#define IDC_WHITE_BUTTON                1077
#define IDC_PROTECT_BUTTON              1078
#define IDC_PROTECT_LIST                1079
#define IDC_PROTECT_EDIT2               1080
#define IDC_DELETE_BUTTON               1082
#define IDC_INFO_LIST                   1083
#define IDC_ACT_EDIT                    1085
#define IDC_BEGIN_BUTTON                1088
#define IDC_STOP_BUTTON                 1089
#define IDC_CHECK2                      1092
#define IDC_INFO_STATIC                 1092
#define IDC_CHECK3                      1093
#define IDC_TESTCOUNT                   1093
#define IDC_CHECK4                      1094
#define IDM_BASIC                       32771
#define ID_BUTTON32772                  32772
#define ID_BUTTON32773                  32773
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_BUTTON32777                  32777
#define ID_BUTTON32778                  32778
#define ID_ERROR                        32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define IDM_PROTECT                     32782
#define IDM_PROCESS_REFRESH             32787
#define IDM_PROCESS_END                 32789
#define IDM_PROCESS_MODULE              32790
#define IDM_HELP                        32791
#define IDM_CONNECT_REFRESH             32793
#define IDM_CONNECT_END                 32794
#define IDM_ATTACKLOG_REFRESH           32795
#define IDM_ATTACKLOG_SAVE              32796
#define IDR_OPEN                        32797
#define IDR_EXIT                        32798
#define IDM_ATTACKLOG_CLEARALL          32799
#define IDM_SET                         32801
#define IDM_LOG                         32802
#define IDM_SERVICE_REFRESH             32805
#define IDM_SERVICE_START               32806
#define IDM_SERVICE_STOP                32807
#define IDM_SERVICE_AUTO                32808
#define IDM_SERVICE_MANUAL              32809
#define IDM_SERVICE_DISABLE             32810
#define ID_MENUITEM32814                32814
#define ID_MENUITEM32815                32815
#define IDM_AUTORUN_REFRESH             32816
#define IDM_AUTORUN_DELETE              32817
#define IDM_HOSTS_CHANGE                32818
#define IDM_HOSTS_DELETE                32819
#define IDM_HOSTS_NEW                   32820
#define IDM_HOSTS_SAVE                  32821
#define ID_MENUITEM32822                32822
#define IDM_HOSTS_REFRESH               32823
#define IDM_DEL                         32824
#define IDM_NEWHOST                     32825
#define IDM_DELHOST                     32826
#define IDM_NETSHOW                     32827
#define IDM_HOSTSHOW                    32828
#define ID_MENUITEM32829                32829
#define IDM_DELETE                      32830
#define IDM_DELETEALL                   32831
#define ID_MENUITEM32834                32834
#define IDS_MYSTATUS                    57346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
